### ISSUE TITLE
res support question?

### ISSUE THREAD

**Issue by DemonRem** [hongha1412/swadmin#12]
can you add the following res files to be supported?
table.res
tb_Day_Event.res
tb_Echelon.res

**Comment by hongha1412** [comment]
Added server side, still not have time for client side
https://github.com/hongha1412/swadmin/commit/d831ee4a9c4d1ab96b2b897a6a6bf37b12ca5e80

**Comment by DemonRem** [comment]
But not all res are there

**Comment by hongha1412** [comment]
> But not all res are there

Yes, i just make base code and very common res file
res file are too much, can't define it all by my self
Project just have GreenDamTan support, i think no one interested in it :)

**Comment by DemonRem** [comment]
i wish i can help but my knowledge not good in this,
if there something i can do to help tell me.

**Comment by hongha1412** [comment]
@DemonRem thank you so much
if you have structure of server/client side, you can just send it to me, and i'll add into sourcecode

**Comment by hongha1412** [comment]
@DemonRem I've added all server's res file, structure generated by IDA (not manually define) so, maybe it works perfectly, maybe checksum not works, please check
https://github.com/hongha1412/swadmin/commit/3faed39ae71ea9e6078b5c2da1d732f5ba9f666f
