### ISSUE TITLE
how to add surport about edit client file "tb_Speech_String.res"?

### ISSUE THREAD

**Issue by XiangGong-2020** [hongha1412/swadmin#15]
bro, how to add surport about edit client file "tb_Speech_String.res"? bcz it include almost all stings that need to translate. so it.s important. plz help!

**Comment by XiangGong-2020** [comment]
struct for "tb_Speech_String.res" , may look at https://gist.github.com/x1nixmzeng/a4a5c419f1cd4bc72cba30d5e647bc4f

**Comment by XiangGong-2020** [comment]
I'm very sorry about my little programming knowledge。

**Comment by hongha1412** [comment]
> bro, how to add surport about edit client file "tb_Speech_String.res"? bcz it include almost all stings that need to translate. so it.s important. plz help!

You need to know tb_Speech_String.res's struct. After that look inside SWAdmin/TableStruct/Client directory and try to make a struct file like other file inside this directory.
Remember to keep variable name like what it is except tables's column name.
Or wait until i have free time, i'll try to add into SWAdmin

**Comment by XiangGong-2020** [comment]
ok, thks bro! i wait you,.
Before I learned a little bit of compilation skills, I had no idea how to compile those files.

**Comment by hongha1412** [comment]
> ok, thks bro! i wait you,.
> Before I learned a little bit of compilation skills, I had no idea how to compile those files.

Re-download the SWAdmin.exe, added tb_Speech_String

**Comment by XiangGong-2020** [comment]
thks bro, i will download it, and maybe llearn some basic knowledge of compile.
